/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'documents' : null } |
  { 'clothing' : null } |
  { 'accessories' : null } |
  { 'other' : null } |
  { 'keys' : null } |
  { 'books' : null } |
  { 'electronics' : null };
export interface Claim {
  'id' : ClaimId,
  'status' : ClaimStatus,
  'itemId' : ItemId,
  'createdAt' : Timestamp,
  'message' : string,
  'claimantId' : UserId,
}
export type ClaimId = bigint;
export type ClaimStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface CreateClaimRequest { 'itemId' : ItemId, 'message' : string }
export interface CreateItemRequest {
  'date' : Timestamp,
  'name' : string,
  'description' : string,
  'imageUrl' : [] | [string],
  'itemType' : ItemType,
  'category' : Category,
  'location' : string,
}
export interface Item {
  'id' : ItemId,
  'status' : ItemStatus,
  'userId' : UserId,
  'date' : Timestamp,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'imageUrl' : [] | [string],
  'itemType' : ItemType,
  'category' : Category,
  'location' : string,
}
export type ItemId = bigint;
export type ItemStatus = { 'resolved' : null } |
  { 'open' : null } |
  { 'matched' : null };
export type ItemType = { 'found' : null } |
  { 'lost' : null };
export interface ItemsPage {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<Item>,
}
export interface Notification {
  'id' : NotificationId,
  'itemId' : [] | [ItemId],
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : boolean,
  'message' : string,
}
export type NotificationId = bigint;
export type NotificationType = { 'claim_approved' : null } |
  { 'claim_rejected' : null } |
  { 'match_found' : null } |
  { 'claim_received' : null };
export type Timestamp = bigint;
export interface UpdateItemRequest {
  'id' : ItemId,
  'name' : [] | [string],
  'description' : [] | [string],
  'imageUrl' : [] | [string],
  'location' : [] | [string],
}
export interface UpdateUserRequest {
  'name' : [] | [string],
  'email' : [] | [string],
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
}
export interface _SERVICE {
  'approveClaim' : ActorMethod<[ClaimId], boolean>,
  'createItem' : ActorMethod<[CreateItemRequest], Item>,
  'deleteItem' : ActorMethod<[ItemId], boolean>,
  'getItem' : ActorMethod<[ItemId], [] | [Item]>,
  'getMatchSuggestions' : ActorMethod<[ItemId], Array<Item>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'listAllItems' : ActorMethod<[bigint, bigint], ItemsPage>,
  'listClaimsByItem' : ActorMethod<[ItemId], Array<Claim>>,
  'listItemsByCategory' : ActorMethod<[Category, bigint, bigint], ItemsPage>,
  'listItemsByType' : ActorMethod<[ItemType, bigint, bigint], ItemsPage>,
  'listItemsByUser' : ActorMethod<[UserId], Array<Item>>,
  'listMyClaims' : ActorMethod<[], Array<Claim>>,
  'markNotificationRead' : ActorMethod<[NotificationId], boolean>,
  'registerUser' : ActorMethod<[string, string], UserProfile>,
  'rejectClaim' : ActorMethod<[ClaimId], boolean>,
  'resolveItem' : ActorMethod<[ItemId], boolean>,
  'submitClaim' : ActorMethod<[CreateClaimRequest], Claim>,
  'updateItem' : ActorMethod<[UpdateItemRequest], [] | [Item]>,
  'updateMyProfile' : ActorMethod<[UpdateUserRequest], [] | [UserProfile]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];