/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ClaimId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ItemType = IDL.Variant({ 'found' : IDL.Null, 'lost' : IDL.Null });
export const Category = IDL.Variant({
  'documents' : IDL.Null,
  'clothing' : IDL.Null,
  'accessories' : IDL.Null,
  'other' : IDL.Null,
  'keys' : IDL.Null,
  'books' : IDL.Null,
  'electronics' : IDL.Null,
});
export const CreateItemRequest = IDL.Record({
  'date' : Timestamp,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'itemType' : ItemType,
  'category' : Category,
  'location' : IDL.Text,
});
export const ItemId = IDL.Nat;
export const ItemStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'open' : IDL.Null,
  'matched' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Item = IDL.Record({
  'id' : ItemId,
  'status' : ItemStatus,
  'userId' : UserId,
  'date' : Timestamp,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'itemType' : ItemType,
  'category' : Category,
  'location' : IDL.Text,
});
export const NotificationId = IDL.Nat;
export const NotificationType = IDL.Variant({
  'claim_approved' : IDL.Null,
  'claim_rejected' : IDL.Null,
  'match_found' : IDL.Null,
  'claim_received' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : NotificationId,
  'itemId' : IDL.Opt(ItemId),
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
  'message' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
});
export const ItemsPage = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'items' : IDL.Vec(Item),
});
export const ClaimStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Claim = IDL.Record({
  'id' : ClaimId,
  'status' : ClaimStatus,
  'itemId' : ItemId,
  'createdAt' : Timestamp,
  'message' : IDL.Text,
  'claimantId' : UserId,
});
export const CreateClaimRequest = IDL.Record({
  'itemId' : ItemId,
  'message' : IDL.Text,
});
export const UpdateItemRequest = IDL.Record({
  'id' : ItemId,
  'name' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const UpdateUserRequest = IDL.Record({
  'name' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'approveClaim' : IDL.Func([ClaimId], [IDL.Bool], []),
  'createItem' : IDL.Func([CreateItemRequest], [Item], []),
  'deleteItem' : IDL.Func([ItemId], [IDL.Bool], []),
  'getItem' : IDL.Func([ItemId], [IDL.Opt(Item)], ['query']),
  'getMatchSuggestions' : IDL.Func([ItemId], [IDL.Vec(Item)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'listAllItems' : IDL.Func([IDL.Nat, IDL.Nat], [ItemsPage], ['query']),
  'listClaimsByItem' : IDL.Func([ItemId], [IDL.Vec(Claim)], ['query']),
  'listItemsByCategory' : IDL.Func(
      [Category, IDL.Nat, IDL.Nat],
      [ItemsPage],
      ['query'],
    ),
  'listItemsByType' : IDL.Func(
      [ItemType, IDL.Nat, IDL.Nat],
      [ItemsPage],
      ['query'],
    ),
  'listItemsByUser' : IDL.Func([UserId], [IDL.Vec(Item)], ['query']),
  'listMyClaims' : IDL.Func([], [IDL.Vec(Claim)], ['query']),
  'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
  'rejectClaim' : IDL.Func([ClaimId], [IDL.Bool], []),
  'resolveItem' : IDL.Func([ItemId], [IDL.Bool], []),
  'submitClaim' : IDL.Func([CreateClaimRequest], [Claim], []),
  'updateItem' : IDL.Func([UpdateItemRequest], [IDL.Opt(Item)], []),
  'updateMyProfile' : IDL.Func([UpdateUserRequest], [IDL.Opt(UserProfile)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ClaimId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ItemType = IDL.Variant({ 'found' : IDL.Null, 'lost' : IDL.Null });
  const Category = IDL.Variant({
    'documents' : IDL.Null,
    'clothing' : IDL.Null,
    'accessories' : IDL.Null,
    'other' : IDL.Null,
    'keys' : IDL.Null,
    'books' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const CreateItemRequest = IDL.Record({
    'date' : Timestamp,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'itemType' : ItemType,
    'category' : Category,
    'location' : IDL.Text,
  });
  const ItemId = IDL.Nat;
  const ItemStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'open' : IDL.Null,
    'matched' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Item = IDL.Record({
    'id' : ItemId,
    'status' : ItemStatus,
    'userId' : UserId,
    'date' : Timestamp,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'itemType' : ItemType,
    'category' : Category,
    'location' : IDL.Text,
  });
  const NotificationId = IDL.Nat;
  const NotificationType = IDL.Variant({
    'claim_approved' : IDL.Null,
    'claim_rejected' : IDL.Null,
    'match_found' : IDL.Null,
    'claim_received' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : NotificationId,
    'itemId' : IDL.Opt(ItemId),
    'userId' : UserId,
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
    'message' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
  });
  const ItemsPage = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(Item),
  });
  const ClaimStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Claim = IDL.Record({
    'id' : ClaimId,
    'status' : ClaimStatus,
    'itemId' : ItemId,
    'createdAt' : Timestamp,
    'message' : IDL.Text,
    'claimantId' : UserId,
  });
  const CreateClaimRequest = IDL.Record({
    'itemId' : ItemId,
    'message' : IDL.Text,
  });
  const UpdateItemRequest = IDL.Record({
    'id' : ItemId,
    'name' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const UpdateUserRequest = IDL.Record({
    'name' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'approveClaim' : IDL.Func([ClaimId], [IDL.Bool], []),
    'createItem' : IDL.Func([CreateItemRequest], [Item], []),
    'deleteItem' : IDL.Func([ItemId], [IDL.Bool], []),
    'getItem' : IDL.Func([ItemId], [IDL.Opt(Item)], ['query']),
    'getMatchSuggestions' : IDL.Func([ItemId], [IDL.Vec(Item)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'listAllItems' : IDL.Func([IDL.Nat, IDL.Nat], [ItemsPage], ['query']),
    'listClaimsByItem' : IDL.Func([ItemId], [IDL.Vec(Claim)], ['query']),
    'listItemsByCategory' : IDL.Func(
        [Category, IDL.Nat, IDL.Nat],
        [ItemsPage],
        ['query'],
      ),
    'listItemsByType' : IDL.Func(
        [ItemType, IDL.Nat, IDL.Nat],
        [ItemsPage],
        ['query'],
      ),
    'listItemsByUser' : IDL.Func([UserId], [IDL.Vec(Item)], ['query']),
    'listMyClaims' : IDL.Func([], [IDL.Vec(Claim)], ['query']),
    'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [UserProfile], []),
    'rejectClaim' : IDL.Func([ClaimId], [IDL.Bool], []),
    'resolveItem' : IDL.Func([ItemId], [IDL.Bool], []),
    'submitClaim' : IDL.Func([CreateClaimRequest], [Claim], []),
    'updateItem' : IDL.Func([UpdateItemRequest], [IDL.Opt(Item)], []),
    'updateMyProfile' : IDL.Func(
        [UpdateUserRequest],
        [IDL.Opt(UserProfile)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };