/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Claim {
    id: ClaimId;
    status: ClaimStatus;
    itemId: ItemId;
    createdAt: Timestamp;
    message: string;
    claimantId: UserId;
}
export type Timestamp = bigint;
export interface CreateItemRequest {
    date: Timestamp;
    name: string;
    description: string;
    imageUrl?: string;
    itemType: ItemType;
    category: Category;
    location: string;
}
export interface CreateClaimRequest {
    itemId: ItemId;
    message: string;
}
export type UserId = Principal;
export interface ItemsPage {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<Item>;
}
export interface Item {
    id: ItemId;
    status: ItemStatus;
    userId: UserId;
    date: Timestamp;
    name: string;
    createdAt: Timestamp;
    description: string;
    imageUrl?: string;
    itemType: ItemType;
    category: Category;
    location: string;
}
export type NotificationId = bigint;
export interface UpdateItemRequest {
    id: ItemId;
    name?: string;
    description?: string;
    imageUrl?: string;
    location?: string;
}
export interface Notification {
    id: NotificationId;
    itemId?: ItemId;
    userId: UserId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    read: boolean;
    message: string;
}
export interface UpdateUserRequest {
    name?: string;
    email?: string;
}
export type ItemId = bigint;
export interface UserProfile {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    email: string;
}
export type ClaimId = bigint;
export enum Category {
    documents = "documents",
    clothing = "clothing",
    accessories = "accessories",
    other = "other",
    keys = "keys",
    books = "books",
    electronics = "electronics"
}
export enum ClaimStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ItemStatus {
    resolved = "resolved",
    open = "open",
    matched = "matched"
}
export enum ItemType {
    found = "found",
    lost = "lost"
}
export enum NotificationType {
    claim_approved = "claim_approved",
    claim_rejected = "claim_rejected",
    match_found = "match_found",
    claim_received = "claim_received"
}
export interface backendInterface {
    approveClaim(claimId: ClaimId): Promise<boolean>;
    createItem(request: CreateItemRequest): Promise<Item>;
    deleteItem(id: ItemId): Promise<boolean>;
    getItem(id: ItemId): Promise<Item | null>;
    getMatchSuggestions(id: ItemId): Promise<Array<Item>>;
    getMyNotifications(): Promise<Array<Notification>>;
    getMyProfile(): Promise<UserProfile | null>;
    getUserProfile(userId: UserId): Promise<UserProfile | null>;
    listAllItems(offset: bigint, limit: bigint): Promise<ItemsPage>;
    listClaimsByItem(itemId: ItemId): Promise<Array<Claim>>;
    listItemsByCategory(category: Category, offset: bigint, limit: bigint): Promise<ItemsPage>;
    listItemsByType(itemType: ItemType, offset: bigint, limit: bigint): Promise<ItemsPage>;
    listItemsByUser(userId: UserId): Promise<Array<Item>>;
    listMyClaims(): Promise<Array<Claim>>;
    markNotificationRead(id: NotificationId): Promise<boolean>;
    registerUser(name: string, email: string): Promise<UserProfile>;
    rejectClaim(claimId: ClaimId): Promise<boolean>;
    resolveItem(id: ItemId): Promise<boolean>;
    submitClaim(request: CreateClaimRequest): Promise<Claim>;
    updateItem(request: UpdateItemRequest): Promise<Item | null>;
    updateMyProfile(request: UpdateUserRequest): Promise<UserProfile | null>;
}
import type { Category as _Category, Claim as _Claim, ClaimId as _ClaimId, ClaimStatus as _ClaimStatus, CreateItemRequest as _CreateItemRequest, Item as _Item, ItemId as _ItemId, ItemStatus as _ItemStatus, ItemType as _ItemType, ItemsPage as _ItemsPage, Notification as _Notification, NotificationId as _NotificationId, NotificationType as _NotificationType, Timestamp as _Timestamp, UpdateItemRequest as _UpdateItemRequest, UpdateUserRequest as _UpdateUserRequest, UserId as _UserId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approveClaim(arg0: ClaimId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveClaim(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveClaim(arg0);
            return result;
        }
    }
    async createItem(arg0: CreateItemRequest): Promise<Item> {
        if (this.processError) {
            try {
                const result = await this.actor.createItem(to_candid_CreateItemRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Item_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createItem(to_candid_CreateItemRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Item_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteItem(arg0: ItemId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteItem(arg0);
            return result;
        }
    }
    async getItem(arg0: ItemId): Promise<Item | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItem(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItem(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchSuggestions(arg0: ItemId): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchSuggestions(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchSuggestions(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllItems(arg0: bigint, arg1: bigint): Promise<ItemsPage> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllItems(arg0, arg1);
                return from_candid_ItemsPage_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllItems(arg0, arg1);
            return from_candid_ItemsPage_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listClaimsByItem(arg0: ItemId): Promise<Array<Claim>> {
        if (this.processError) {
            try {
                const result = await this.actor.listClaimsByItem(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClaimsByItem(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async listItemsByCategory(arg0: Category, arg1: bigint, arg2: bigint): Promise<ItemsPage> {
        if (this.processError) {
            try {
                const result = await this.actor.listItemsByCategory(to_candid_Category_n5(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_ItemsPage_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listItemsByCategory(to_candid_Category_n5(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_ItemsPage_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listItemsByType(arg0: ItemType, arg1: bigint, arg2: bigint): Promise<ItemsPage> {
        if (this.processError) {
            try {
                const result = await this.actor.listItemsByType(to_candid_ItemType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_ItemsPage_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listItemsByType(to_candid_ItemType_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_ItemsPage_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listItemsByUser(arg0: UserId): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.listItemsByUser(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listItemsByUser(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyClaims(): Promise<Array<Claim>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyClaims();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyClaims();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async markNotificationRead(arg0: NotificationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1);
            return result;
        }
    }
    async rejectClaim(arg0: ClaimId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectClaim(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectClaim(arg0);
            return result;
        }
    }
    async resolveItem(arg0: ItemId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveItem(arg0);
            return result;
        }
    }
    async submitClaim(arg0: CreateClaimRequest): Promise<Claim> {
        if (this.processError) {
            try {
                const result = await this.actor.submitClaim(arg0);
                return from_candid_Claim_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitClaim(arg0);
            return from_candid_Claim_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateItem(arg0: UpdateItemRequest): Promise<Item | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItem(to_candid_UpdateItemRequest_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItem(to_candid_UpdateItemRequest_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMyProfile(arg0: UpdateUserRequest): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(to_candid_UpdateUserRequest_n34(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(to_candid_UpdateUserRequest_n34(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ClaimStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClaimStatus): ClaimStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Claim_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Claim): Claim {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ItemStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemStatus): ItemStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ItemType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemType): ItemType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Item_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Item): Item {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ItemsPage_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemsPage): ItemsPage {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Item]): Item | null {
    return value.length === 0 ? null : from_candid_Item_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ItemId]): ItemId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    itemId: [] | [_ItemId];
    userId: _UserId;
    notificationType: _NotificationType;
    createdAt: _Timestamp;
    read: boolean;
    message: string;
}): {
    id: NotificationId;
    itemId?: ItemId;
    userId: UserId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    read: boolean;
    message: string;
} {
    return {
        id: value.id,
        itemId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.itemId)),
        userId: value.userId,
        notificationType: from_candid_NotificationType_n22(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt,
        read: value.read,
        message: value.message
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<_Item>;
}): {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<Item>;
} {
    return {
        total: value.total,
        offset: value.offset,
        limit: value.limit,
        items: from_candid_vec_n17(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ClaimId;
    status: _ClaimStatus;
    itemId: _ItemId;
    createdAt: _Timestamp;
    message: string;
    claimantId: _UserId;
}): {
    id: ClaimId;
    status: ClaimStatus;
    itemId: ItemId;
    createdAt: Timestamp;
    message: string;
    claimantId: UserId;
} {
    return {
        id: value.id,
        status: from_candid_ClaimStatus_n30(_uploadFile, _downloadFile, value.status),
        itemId: value.itemId,
        createdAt: value.createdAt,
        message: value.message,
        claimantId: value.claimantId
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ItemId;
    status: _ItemStatus;
    userId: _UserId;
    date: _Timestamp;
    name: string;
    createdAt: _Timestamp;
    description: string;
    imageUrl: [] | [string];
    itemType: _ItemType;
    category: _Category;
    location: string;
}): {
    id: ItemId;
    status: ItemStatus;
    userId: UserId;
    date: Timestamp;
    name: string;
    createdAt: Timestamp;
    description: string;
    imageUrl?: string;
    itemType: ItemType;
    category: Category;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_ItemStatus_n9(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        date: value.date,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        imageUrl: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.imageUrl)),
        itemType: from_candid_ItemType_n12(_uploadFile, _downloadFile, value.itemType),
        category: from_candid_Category_n14(_uploadFile, _downloadFile, value.category),
        location: value.location
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    open: null;
} | {
    matched: null;
}): ItemStatus {
    return "resolved" in value ? ItemStatus.resolved : "open" in value ? ItemStatus.open : "matched" in value ? ItemStatus.matched : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    found: null;
} | {
    lost: null;
}): ItemType {
    return "found" in value ? ItemType.found : "lost" in value ? ItemType.lost : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    documents: null;
} | {
    clothing: null;
} | {
    accessories: null;
} | {
    other: null;
} | {
    keys: null;
} | {
    books: null;
} | {
    electronics: null;
}): Category {
    return "documents" in value ? Category.documents : "clothing" in value ? Category.clothing : "accessories" in value ? Category.accessories : "other" in value ? Category.other : "keys" in value ? Category.keys : "books" in value ? Category.books : "electronics" in value ? Category.electronics : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    claim_approved: null;
} | {
    claim_rejected: null;
} | {
    match_found: null;
} | {
    claim_received: null;
}): NotificationType {
    return "claim_approved" in value ? NotificationType.claim_approved : "claim_rejected" in value ? NotificationType.claim_rejected : "match_found" in value ? NotificationType.match_found : "claim_received" in value ? NotificationType.claim_received : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ClaimStatus {
    return "pending" in value ? ClaimStatus.pending : "approved" in value ? ClaimStatus.approved : "rejected" in value ? ClaimStatus.rejected : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Item>): Array<Item> {
    return value.map((x)=>from_candid_Item_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Claim>): Array<Claim> {
    return value.map((x)=>from_candid_Claim_n28(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_CreateItemRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateItemRequest): _CreateItemRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ItemType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): _ItemType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateItemRequest_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateItemRequest): _UpdateItemRequest {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateUserRequest_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateUserRequest): _UpdateUserRequest {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: Timestamp;
    name: string;
    description: string;
    imageUrl?: string;
    itemType: ItemType;
    category: Category;
    location: string;
}): {
    date: _Timestamp;
    name: string;
    description: string;
    imageUrl: [] | [string];
    itemType: _ItemType;
    category: _Category;
    location: string;
} {
    return {
        date: value.date,
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        itemType: to_candid_ItemType_n3(_uploadFile, _downloadFile, value.itemType),
        category: to_candid_Category_n5(_uploadFile, _downloadFile, value.category),
        location: value.location
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ItemId;
    name?: string;
    description?: string;
    imageUrl?: string;
    location?: string;
}): {
    id: _ItemId;
    name: [] | [string];
    description: [] | [string];
    imageUrl: [] | [string];
    location: [] | [string];
} {
    return {
        id: value.id,
        name: value.name ? candid_some(value.name) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name?: string;
    email?: string;
}): {
    name: [] | [string];
    email: [] | [string];
} {
    return {
        name: value.name ? candid_some(value.name) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): {
    found: null;
} | {
    lost: null;
} {
    return value == ItemType.found ? {
        found: null
    } : value == ItemType.lost ? {
        lost: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    documents: null;
} | {
    clothing: null;
} | {
    accessories: null;
} | {
    other: null;
} | {
    keys: null;
} | {
    books: null;
} | {
    electronics: null;
} {
    return value == Category.documents ? {
        documents: null
    } : value == Category.clothing ? {
        clothing: null
    } : value == Category.accessories ? {
        accessories: null
    } : value == Category.other ? {
        other: null
    } : value == Category.keys ? {
        keys: null
    } : value == Category.books ? {
        books: null
    } : value == Category.electronics ? {
        electronics: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
